# Generated by Django 4.1.7 on 2023-03-11 08:02

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('compony_handle', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter_skill_name', max_length=120)),
            ],
        ),
        migrations.CreateModel(
            name='JobAvailable',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter_job_name', max_length=120)),
                ('vacancies', models.IntegerField(help_text='Number_of_vacancies_available')),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='company_job_available', to='compony_handle.company')),
                ('skills', models.ManyToManyField(to='job_handle.skill')),
            ],
        ),
        migrations.CreateModel(
            name='JobApplied',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('resume', models.FileField(help_text='Submit Resume', upload_to='UserResume/')),
                ('applied', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='job_user_applied', to='job_handle.jobavailable')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='applied_user', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
