# Generated by Django 4.1.7 on 2023-03-11 08:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bio', models.CharField(help_text='Enter company bio', max_length=120)),
                ('photo', models.ImageField(help_text='Enter Company Profile photo', upload_to='CompanyPhoto/')),
                ('logo', models.ImageField(help_text='Enter Company logo', upload_to='CompanyLogo/')),
                ('date_of_establishment', models.DateField()),
                ('name', models.CharField(help_text='Enter Company name', max_length=120)),
            ],
        ),
    ]
