# Generated by Django 4.1.7 on 2023-03-11 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compony_handle', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='company',
            name='bio',
            field=models.CharField(blank=True, help_text='Enter company bio', max_length=120, null=True),
        ),
        migrations.AlterField(
            model_name='company',
            name='logo',
            field=models.ImageField(blank=True, help_text='Enter Company logo', null=True, upload_to='CompanyLogo/'),
        ),
        migrations.AlterField(
            model_name='company',
            name='photo',
            field=models.ImageField(blank=True, help_text='Enter Company Profile photo', null=True, upload_to='CompanyPhoto/'),
        ),
    ]
